server:
  port: 8083
#  servlet:
#    context-path: /db_guard

spring:
  application:
    name: db-guard

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: org.h2.Driver
          url: jdbc:h2:file:~/db-guard;DB_CLOSE_DELAY=-1
          username: sa
          password:
    hikari:
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000
      maximum-pool-size: 10
      connection-test-query: select 1
      leak-detection-threshold: 5000
      validation-timeout: 3000

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true

  ai:
    mcp:
      server:
        name: db-guard-mcp-server



